# Generated by Django 4.2.5 on 2023-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_description', models.TextField()),
                ('user_image', models.ImageField(upload_to='users')),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
