# Generated by Django 4.2.6 on 2023-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_code_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='lang',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
